### ISSUE TITLE
Oh no.  Error running app. If this keeps happening, please file an issue.

### ISSUE THREAD

**Issue by ChaiBapchya** [siddheshm14/commodity_price_predictor#1]
https://share.streamlit.io/siddheshm14/commodity_price_predictor/main/stockpredictor.py

**Comment by siddheshm14** [comment]
Check it now. The problem occurs as the LSTM model is not deployed it works
on the run time as the app is made in sucha a way that it gives more user
control

**Comment by ChaiBapchya** [comment]
works. thanks!
